export const orders = [
  {
    id: 1,
    username: "John",
    price: 50.25,
    amount: 100,
    action: "buy",
    minBuy: 10 + Math.random() * 5,
  },
  {
    id: 2,
    username: "Alice",
    price: 48.75,
    amount: 75,
    action: "sell",
    minSell: 7.5 + Math.random() * 3.75,
  },
  {
    id: 3,
    username: "Bob",
    price: 52.0,
    amount: 200,
    action: "buy",
    minBuy: 20 + Math.random() * 10,
  },
  {
    id: 4,
    username: "Eva",
    price: 50.75,
    amount: 150,
    action: "sell",
    minSell: 15 + Math.random() * 7.5,
  },
  {
    id: 5,
    username: "Charlie",
    price: 49.5,
    amount: 100,
    action: "buy",
    minBuy: 10 + Math.random() * 5,
  },
  {
    id: 6,
    username: "Sophia",
    price: 48.25,
    amount: 50,
    action: "sell",
    minSell: 7.5 + Math.random() * 3.75,
  },
  {
    id: 7,
    username: "David",
    price: 50.0,
    amount: 80,
    action: "buy",
    minBuy: 8 + Math.random() * 4,
  },
  {
    id: 8,
    username: "Linda",
    price: 47.75,
    amount: 60,
    action: "sell",
    minSell: 6 + Math.random() * 3,
  },
  {
    id: 9,
    username: "Oliver",
    price: 51.25,
    amount: 120,
    action: "buy",
    minBuy: 12 + Math.random() * 6,
  },
  {
    id: 10,
    username: "Mia",
    price: 48.0,
    amount: 70,
    action: "sell",
    minSell: 7 + Math.random() * 3.5,
  },
  {
    id: 11,
    username: "Daniel",
    price: 52.5,
    amount: 90,
    action: "buy",
    minBuy: 9 + Math.random() * 4.5,
  },
  {
    id: 12,
    username: "Ava",
    price: 49.25,
    amount: 50,
    action: "sell",
    minSell: 7.5 + Math.random() * 3.75,
  },
  {
    id: 13,
    username: "James",
    price: 49.75,
    amount: 150,
    action: "buy",
    minBuy: 15 + Math.random() * 7.5,
  },
  {
    id: 14,
    username: "Olivia",
    price: 47.5,
    amount: 80,
    action: "sell",
    minSell: 8 + Math.random() * 4,
  },
  {
    id: 15,
    username: "Elijah",
    price: 51.0,
    amount: 120,
    action: "buy",
    minBuy: 12 + Math.random() * 6,
  },
  {
    id: 16,
    username: "Amelia",
    price: 48.5,
    amount: 100,
    action: "sell",
    minSell: 10 + Math.random() * 5,
  },
  {
    id: 17,
    username: "William",
    price: 50.5,
    amount: 200,
    action: "buy",
    minBuy: 20 + Math.random() * 10,
  },
  {
    id: 18,
    username: "Charlotte",
    price: 48.75,
    amount: 150,
    action: "sell",
    minSell: 15 + Math.random() * 7.5,
  },
];
